### PR TITLE
`xnat_web_server.url` should include the exposed port

### LINKED ISSUE #75: 🐛 [BUG]: XNAT `site_url` is set without port number
### Bug Description

 If the web port is not 80/443, then it redirects sometimes don’t resolve. For example, in https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT we are using port `8080`.

### Acceptance Criteria

```[tasklist]
### Related Work Items
```

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #75. Would be nice to do this as a variable, but not sure how easy that would be to do. Essentially the same change as in UCL-MIRSG/UCLH-MPBE-SRR-XNAT#198.

### CODE REVIEW

**Comment by paddyroddy** [comment]
```
fatal: [xnat_web]: FAILED! => {"attempts": 10, "changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://xnat.web.local:8000/"}
```
Hmm, not too sure I understand what you guys are doing with ports. Can anyone help @UCL-MIRSG/mirsg?

**Comment by p-j-smith** [comment]
I'm not sure adding the port is necessary? I think the url is already set with the port:
https://github.com/UCL-MIRSG/ansible-collection-infra/blob/163a8ddc552b0131df71e9e44ae67b0f582a6d01/roles/xnat/templates/gradle.properties.j2#L9
Or is `xnatUrl` not where the issue is?

**Comment by paddyroddy** [comment]
> I'm not sure adding the port is necessary? I think the url is already set with the port:
> 
> https://github.com/UCL-MIRSG/ansible-collection-infra/blob/163a8ddc552b0131df71e9e44ae67b0f582a6d01/roles/xnat/templates/gradle.properties.j2#L9
> 
> Or is `xnatUrl` not where the issue is?

The current set up doesn't work, unless the port is `80`/`443`. You get kicked off when a redirect fails. @HChughtai may be able to give a better explanation.

**Comment by HChughtai** [comment]
> I'm not sure adding the port is necessary? I think the url is already set with the port:
> 
> https://github.com/UCL-MIRSG/ansible-collection-infra/blob/163a8ddc552b0131df71e9e44ae67b0f582a6d01/roles/xnat/templates/gradle.properties.j2#L9
> 
> 
> Or is `xnatUrl` not where the issue is?

This is the internal Tomcat port. What Paddy's referring to is this being set with just the url and not a port: https://github.com/UCL-MIRSG/ansible-collection-infra/blob/main/roles/xnat/templates/prefs-init.j2#L4

In normal cases that doesn't make a difference as it's `http/80` or `https/443` and the port and protocol are defaults. In testing and non standard set-ups that port could be something arbitary (e.g. 8080). In those cases, if teh site URL doesn't include the port, XNAT will redirect to the wrong location and hit an error.

**Comment by HChughtai** [comment]
With molecule testing is it similar to Docker where you need to expose ports? If so, I expect theres some test config to be done as well

**Comment by paddyroddy** [comment]
@p-j-smith in SRR we map `8080:80` https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/83f6aa1de30c72ddacb7b0486229a3c6d4e873f8/docker-compose.yml#L117C9-L117C13 so `8080` is exposed, and that is what should be in site URL. By default, HTTP would look for `80` which is what the current set up is doing. In my case, `80` wouldn't work, so we need `8080` to be explicitly set for the URL. Does that make sense?

Are you using HTTP or HTTPS in your `molecule` tests?

**Comment by drmatthews** [comment]
> Are you using HTTP or HTTPS in your molecule tests?

Just to chip in - HTTP. The published ports are here:

https://github.com/UCL-MIRSG/ansible-collection-infra/blob/163a8ddc552b0131df71e9e44ae67b0f582a6d01/playbooks/molecule/rocky9_xnat/molecule.yml#L73-L74

`8080` is exposed but not published:

https://github.com/UCL-MIRSG/ansible-collection-infra/blob/163a8ddc552b0131df71e9e44ae67b0f582a6d01/playbooks/molecule/rocky9_xnat/molecule.yml#L68-L72

(There is an equivalent config for `centos7` - https://github.com/UCL-MIRSG/ansible-collection-infra/blob/main/playbooks/molecule/centos7_xnat/molecule.yml)

**Comment by p-j-smith** [comment]
@paddyroddy I'm not sure but I think you might also need to expose port 8080 of the web container to other containers on the network

**Comment by paddyroddy** [comment]
> @paddyroddy I'm not sure but I think you might also need to expose port 8080 of the web container to other containers on the network

I haven't had to in SRR

**Comment by p-j-smith** [comment]
> I haven't had to in SRR

oh I meant you might need to do it for SRR - it's already done here as @drmatthews linked to

**Comment by paddyroddy** [comment]
> > I haven't had to in SRR
> 
> oh I meant you might need to do it for SRR - it's already done here as @drmatthews linked to

I don't follow. SRR is working.

**Comment by p-j-smith** [comment]
> In normal cases that doesn't make a difference as it's http/80 or https/443 and the port and protocol are defaults. In testing and non standard set-ups that port could be something arbitary (e.g. 8080). In those cases, if teh site URL doesn't include the port, XNAT will redirect to the wrong location and hit an error.

wouldn't it be better to force users to connect via nginx (on port 80 or 443) rather than access 8080 directly?

**Comment by drmatthews** [comment]
@paddyroddy, question: why do you need to use `8080`? Is it something to do with [setting the xnat_web hostname to "localhost"](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/83f6aa1de30c72ddacb7b0486229a3c6d4e873f8/ansible/dev/hosts.yml#L14-L17)?

**Comment by drmatthews** [comment]
I didn't phrase that very well.  I'm wondering why the [hostname for `xnat_web` is set to "localhost"](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/83f6aa1de30c72ddacb7b0486229a3c6d4e873f8/ansible/dev/hosts.yml#L14-L17). But I assume `8080` because you can't bind to `80` on the Docker host, hence:

https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/83f6aa1de30c72ddacb7b0486229a3c6d4e873f8/docker-compose.yml#L116-L117

**Comment by HChughtai** [comment]
> My understanding: in SRR, externally XNAT is accessible via `8080`. That port binds to `80` in the `xnat_web` container. In the container `nginx` is listening on `80` and reverse proxying to `tomcat` (which is on `8080` inside the container).

This is only true in Paddy's dev setup (using `localhost:8080` so it can't conflict with anything else running at `localhost:80`), on the production instance it's setup to use port 80 with the server's hostname. So it's a generalisation point if I understand correctly. It should be possible to run a web service on a non-standard port and have it function correctly.

**Comment by paddyroddy** [comment]
> @paddyroddy, question: why do you need to use `8080`? Is it something to do with [setting the xnat_web hostname to "localhost"](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/83f6aa1de30c72ddacb7b0486229a3c6d4e873f8/ansible/dev/hosts.yml#L14-L17)?

`8080` was @HChughtai's idea

**Comment by paddyroddy** [comment]
I didn't realise that `tomcat` uses `8080`. I was under the impression that `>=8000` was unreserved

**Comment by HChughtai** [comment]
> I didn't realise that `tomcat` uses `8080`. I was under the impression that `>=8000` was unreserved

Widely used, rather than reserved. It's also widely used as an alternative to `80` (which is why I used it) See https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers. It is also used by our Tomcat definition, but in a different scope to publishing it on your host

**Comment by paddyroddy** [comment]
(fixing in #79)

**Pull request closed without merging**
