### PR TITLE
Fix molecule prepare playbooks

### LINKED ISSUE #113: All `molecule-` tests should be run on pushes to `main`
### Short Description

Either they should always be tested OR we have a 2 branch workflow where relevant ones are run on merges to `dev` BUT all are run on pushes to `main`.

There are recent changes that have broken `main`, but sneaked in due to not being tested. Relvant bugs: #111

### Evidence/Steps to Reproduce

_No response_

### Acceptance Criteria/Expected Behaviour

_No response_

### Details

_No response_

### Resolution

_No response_

### PR DESCRIPTION
**Pull request by drmatthews**
Changes:

- Handle Rocky8 by renaming `roles/provision/tasks/RedHat9.yml` to `roles/provision/tasks/RedHat.yml` and including when `ansible_distribution_major_version` is not `7`.
- Fix all the broken `prepare.yml` playbooks used by `molecule`
- Changed triggers to run all tests on all PRs (closes #113)

### CODE REVIEW

**Review by p-j-smith — CHANGES_REQUESTED** [review]
thanks for fixing! Should we run all tests on every PR?

**Review by p-j-smith — APPROVED** [review]
👍

**Comment by drmatthews** [comment]
@p-j-smith - soz for another review! Changed the workflow triggers for `postgresql_upgrade` and `provision_accounts` back.

**Review by p-j-smith — APPROVED** [review]
looks good

**Pull request merged**
