### PR TITLE
versioning should be defined as a `PackageRule`

### LINKED ISSUE #6: Action Required: Fix Renovate Configuration
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Location: `.renovaterc.json5`
Error type: Invalid JSON5 (parsing failed)
Message: JSON5.parse error: `JSON5: invalid character ',' at 34:5`

### PR DESCRIPTION
**Pull request by p-j-smith**
Fixes #6 

- define versioning to use as part of the `PackageRule` for the `xnat` group

### CODE REVIEW

**Review by paddyroddy — APPROVED** [review]
Once this is merged, make sure you verify that it works at developer.mend.io

**Comment by p-j-smith** [comment]
sorry I had to fix a linting error

**Comment by paddyroddy** [comment]
> sorry I had to fix a linting error

I did see that, added a ruleset to make linting mandatory 😁

**Review by paddyroddy — APPROVED** [review]
🫐

**Comment by p-j-smith** [comment]
> Once this is merged, make sure you verify that it works at developer.mend.io

No more versioning complaints, but #49 is still an issue

**Pull request merged**
