### PR TITLE
Remove reusable workflow across molecule tests

### PR DESCRIPTION
**Pull request by paddyroddy**
In the process of fixing things around #115, we want to use different options in the composite action related to https://github.com/UCL-MIRSG/.github/pull/121 & https://github.com/UCL-MIRSG/.github/pull/122. This would mean we'd need to set extra options in the reusable workflow, which will get confusing. By removing the reusable workflow, this will simplify things greatly. This will lead to more verbose code, but better in the long-term.

### CODE REVIEW

**Review by HChughtai — COMMENTED** [review]
See comment in https://github.com/UCL-MIRSG/ansible-collection-infra/issues/115#issuecomment-2149813892 about pinning to major version of Ansible instead.

Additionally, could we specify the `ansible_version` in a repo or org wide variable? And then when we want to move to Ansible `10.x.x` we'd only need to change in one place?

**Comment by paddyroddy** [comment]
> See comment in [#115 (comment)](https://github.com/UCL-MIRSG/ansible-collection-infra/issues/115#issuecomment-2149813892) about pinning to major version of Ansible instead.
> 
> Additionally, could we specify the `ansible_version` in a repo or org wide variable? And then when we want to move to Ansible `10.x.x` we'd only need to change in one place?

Nice idea, incoming

**Comment by paddyroddy** [comment]
I have updated the actions to use the major Ansible version. If actions pass, then assume this is good to go.

**Comment by paddyroddy** [comment]
@HChughtai the ones that are failing are due to the whole `paths:` mess and me updating manually `pip install ansible==${{ vars.ANSIBLE_MAJOR_VERSION }}.*` so they can be ignored

**Review by HChughtai — APPROVED** [review]

**Pull request merged**
